### ISSUE TITLE
[Bug]: Problem opening bloons TD6 epic games

### ISSUE THREAD

**Issue by jpparella** [LavaGang/MelonLoader#537]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

I have this problem, I tried to install the loader, I even put it in a previous version to test, but it doesn't work
When starting the game (through epic games, through the game folder, through the game folder as administrator)
The loader screen appears and then it appears that the game has stopped responding

[Latest.log](https://github.com/LavaGang/MelonLoader/files/12795773/Latest.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment]
Try updating MelonLoader to version 0.6.1 and also BTD6 Epic Games Mod Compat to 1.2.1

**Comment by jpparella** [comment]
I have already updated the latest version of BTD6EpicGamesModCompat that is available
When you download 1.2.1 in the log it becomes 1.2.0....
And I also tested with the updated loader, in the log I sent it was with the old version but the new one also happens the same thing
[Latest.log](https://github.com/LavaGang/MelonLoader/files/12796133/Latest.log)
