### ISSUE TITLE
[Crash]: my melon loader says its missing dependencies i cant find the one i cant find is steamworks face punch but i use epic games

### ISSUE THREAD

**Issue by Diamondgamer96** [LavaGang/MelonLoader#570]
### All of the following criteria must be met

- [x] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

its in title

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by rakosi2** [comment]
What game is this?

**Comment by Diamondgamer96** [comment]
It is BTD6

**Comment by rakosi2** [comment]
Did you install MelonLoader nightly and it says 0.6.2

**Comment by Diamondgamer96** [comment]
Yes, I did!

**Comment by rakosi2** [comment]
Do you have the epic game compat plugin?

**Comment by Diamondgamer96** [comment]
Yes, I do.

**Comment by rakosi2** [comment]
If you open the MelonLoader folder, do you see a file called Latest or Latest.log?

**Comment by Diamondgamer96** [comment]
i did but i like my btd so i uninstalled melonloader.

**Comment by rakosi2** [comment]
Closing because user no longer has this issue

**Comment by Diamondgamer96** [comment]
no pls i need help with it
