### ISSUE TITLE
[Bug]: Failed to save mod settings when using Epic games version

### ISSUE THREAD

**Issue by Xevets** [LavaGang/MelonLoader#725]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/user-attachments/files/16667083/Latest.log)
Using the latest version of melonloader with the epic games version of BTD6 via the epic games compatability dll the mods are no longer saving any changes made to them.  Melon loader also pops up a dialogue at startup asking if I want to download the epic games compatability dll even though it is installed and loaded successfully in the log.  

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by DarkTerraYT** [comment]
Downgrade melon loader to 0.6.1, always use melon loader 0.6.1 when modding btd6
